name: Bionics
main: Bionics\Main
version: 2.0.0
api:
- 1.0.0
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 4.0.0
load: STARTUP
author: Spiderman
commands:
 ill:
  usage: "/ill 查看药物列表"
  permission: illness.command.ill
 rlset:
  usage: "/rlset true/false [type]"
  permission: illness.command.cmd
permissions:
 illness.command.ill:
  default: true
 illness.command.cmd:
   default: op

